version: '3.4'

services:
  eshopcatalogdb:
    container_name: eshopmongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - catalog_mongo_data:/data/db
        
  eshopapi:
    container_name: catalog.web-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "MongoDbConfiguration:ConnectionString=mongodb://eshopmongodb:27017"
    depends_on:
      - eshopcatalogdb
    ports:
      - "8000:80"